name: main
version: 0.0.1
description: example
type: rewoo
prompt_template:
  - Planner:
      input_variables:
       - foo
      template: "Say {foo}"
  - Solver:
      input_variables:
       - foo
      template: "Say {foo}"
llm:
  - Planner:
      name: guanaco
      description: 111
      model_name: 111123
  - Solver:
      name: guanaco
      description: 122223
      model_name: 123
target_tasks:
 - print
 - find

plugins:
   -  !include config2.yaml
   -  name: main
      version: 0.0.1
      description: example
      type: rewoo
      prompt_template:
        - Planner:
            input_variables:
             - foo
            template: "Say {foo}"
        - Solver:
            input_variables:
             - foo
            template: "Say {foo}"
      llm:
        - Planner:
            name: guanaco
            model_name: 123
            description: 111123
        - Solver:
            name: guanaco
            model_name: 123
            description: 123
      plugins:
        - name: cal
          version: 0.0.1
          description: example
          type: calculator
   -  name: wiki
      version: 0.0.1
      description: example
      type: wikipedia
   -  name: cal

