name: main
version: 0.0.1
description: example
type: rewoo
prompt_template:
  - Planner:
      prompt: !prompt ZeroShotPlannerPrompt
  - Solver:
      prompt: !prompt ZeroShotSolverPrompt
llm:
  - Planner:
      name: guanaco-7b
      description: 111
      model_name: 111123
  - Solver:
      name: guanaco-7b
      description: 122223
      model_name: 123
target_tasks:
 - print
 - find

plugins:
  - name: cal
    version: 0.0.1
    description: example
    type: calculator
  - name: wiki
    version: 0.0.1
    description: example
    type: wikipedia

