# Agent Config
name: main
type: rewoo
version: 0.0.1
description: example
prompt_template:
  Planner: !prompt ZeroShotPlannerPrompt
  Solver: !prompt ZeroShotSolverPrompt
llm:
  Planner:
    model_name: gpt-4
    params:
      temperature: 0.7
  Solver:
    model_name: gpt-4
    params:
      max_tokens: 1024
      temperature: 0.0
      frequency_penalty: 0.0
target_tasks:
 - print
 - find

plugins:
  - !include my_custom_agent.yaml
  - !tool MyCustomTool
  - name: calculator
    params:
      description: example
  - name: wikipedia
    params:
      verbose: true


# Authentication
auth:
  - OPENAI_API_KEY: <YOUR_API_KEY>
