# Agent Config
name: main
type: rewoo
version: 0.0.1
description: main agent leveraging OpenAI function call API.
prompt_template:
  Planner: !prompt ZeroShotPlannerPrompt
  Solver: !prompt ZeroShotSolverPrompt
llm:
  Planner:
    model_name: gpt-3.5-turbo-0613
    params:
      temperature: 0.0
      top_p: 0.9
      repetition_penalty: 1.0
      max_tokens: 1024
  Solver:
    model_name: gpt-3.5-turbo-0613
    params:
      temperature: 0.0
      top_p: 0.9
      repetition_penalty: 1.0
      max_tokens: 1024
target_tasks:
  - calculate sqrt(10)
plugins:
  - name: mathria
    type: vanilla
    description: A math agent capable of solving complicated math problems. Ask it to solve any math problems.
    prompt_template: !prompt ZeroShotVanillaPrompt
    llm:
      model_name: gpt-3.5-turbo-0613
      params:
        temperature: 0.0
        top_p: 1.0
        max_tokens: 1024
    target_tasks:
      - solving math problems
      - answer things about math


# Authentication
auth:
  OPENAI_API_KEY: !file api.key