name: main
version: 0.0.1
description: example
type: React
llm: GPT-4

plugins:
  - !include: ./plugins/React/React-Router.js
  - !include: ./plugins/React/React-Redux.js
  - name: React-Router
    type: React
    llm: pass
    plugins:
      - !include: ./plugins/React/React-Router.js
