# Agent Config
name: main
type: openai
version: 0.0.1
description: main agent leveraging OpenAI function call API.
prompt_template: !prompt VanillaPrompt
llm:
  model_name: gpt-4-0613
  params:
    temperature: 0.0
    top_p: 0.9
    repetition_penalty: 1.0
    max_tokens: 1024
target_tasks:
  - anything
plugins:
  - name: google_search
  - name: web_page
