# Agent Config
name: main
type: vanilla
version: 0.0.1
description: example
prompt_template: !prompt VanillaPrompt
llm:
  model_name: vicuna-7b
  param:
    temperature: 0.6
    top_p: 0.8
    max_new_tokens: 24
  device: gpu
