# Agent Config
name: main
type: rewoo
version: 0.0.1
description: main agent leveraging OpenAI function call API.
prompt_template:
  Planner: !prompt ZeroShotPlannerPrompt
  Solver: !prompt ZeroShotSolverPrompt
llm:
  Planner:
    model_name: gpt-3.5-turbo-0613
    params:
      temperature: 0.0
      top_p: 0.9
      repetition_penalty: 1.0
      max_tokens: 1024
  Solver:
    model_name: gpt-3.5-turbo-0613
    params:
      temperature: 0.0
      top_p: 0.9
      repetition_penalty: 1.0
      max_tokens: 1024
target_tasks:
  - calculate sqrt(10)
plugins:
  - name: google_search
  - name: web_page
  - !include mathria.yaml


# Authentication
auth:
  OPENAI_API_KEY: !file /home/api.key
  WOLFRAM_ALPHA_APPID: !file /home/wolfram.key