# Agent Config
name: main
type: openai_memory
version: 0.0.1
description: main agent leveraging OpenAI function call API.
prompt_template: !prompt VanillaPrompt
memory:
  memory_type: chroma   # chroma or pinecone
  conversation_threshold: 1        # first-level memory
  reasoning_threshold: 1          # second-level memory
  params:
    index: main
    top_k: 2
    # text_key: test    # pinecone need
llm:
  model_name: gpt-4-0613
  params:
    temperature: 0.0
    top_p: 0.9
    repetition_penalty: 1.0
    max_tokens: 1024
target_tasks:
  - anything
plugins:
  - name: google_search
  - name: web_page
  # - !include mathria.yaml


