# Agent Config
name: main
type: react
version: 0.0.1
description: main agent leveraging OpenAI function call API.
prompt_template: !prompt ZeroShotReactPrompt
llm:
  model_name: gpt-3.5-turbo
  params:
    temperature: 0.0
    top_p: 0.9
    repetition_penalty: 1.0
    max_tokens: 1024
target_tasks:
  - anything
plugins:
  - name: google_search
  - name: web_page
  - !include mathria.yaml
#    type: vanilla
#    description: A math agent capable of solving complicated math problems. Ask it to solve any math problems.
#    prompt_template: !prompt ZeroShotVanillaPrompt
#    llm:
#      model_name: gpt-3.5-turbo-0613
#      params:
#        temperature: 0.0
#        top_p: 1.0
#        max_tokens: 1024
#    target_tasks:
#      - solving math problems
#      - answer things about math


## Authentication
#auth:
#  OPENAI_API_KEY: !file /home/api.key
#  WOLFRAM_ALPHA_APPID: !file /home/wolfram.key

